-- MySQL Script generated by MySQL Workbench
-- 07/07/19 20:44:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema domain-vermietet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domain-vermietet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domain-vermietet` DEFAULT CHARACTER SET utf8 ;
USE `domain-vermietet` ;

-- -----------------------------------------------------
-- Table `domain-vermietet`.`userdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`userdetails` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`userdetails` (
  `userdetailsid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`userdetailsid`),
  UNIQUE INDEX `userdetailsid_UNIQUE` (`userdetailsid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`village`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`village` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`village` (
  `villageid` INT NOT NULL AUTO_INCREMENT,
  `villagename` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`villageid`),
  UNIQUE INDEX `villageid_UNIQUE` (`villageid` ASC),
  UNIQUE INDEX `villagename_UNIQUE` (`villagename` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`building`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`building` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`building` (
  `buildingid` INT NOT NULL AUTO_INCREMENT,
  `buildingname` VARCHAR(128) NOT NULL,
  `village` INT NOT NULL,
  PRIMARY KEY (`buildingid`),
  INDEX `fk_building_village_idx` (`village` ASC),
  UNIQUE INDEX `buildingid_UNIQUE` (`buildingid` ASC),
  UNIQUE INDEX `buildingname_UNIQUE` (`buildingname` ASC),
  CONSTRAINT `fk_building_village`
    FOREIGN KEY (`village`)
    REFERENCES `domain-vermietet`.`village` (`villageid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`apartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`apartment` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`apartment` (
  `apartmentid` INT NOT NULL AUTO_INCREMENT,
  `apartmentname` VARCHAR(128) NOT NULL,
  `building` INT NOT NULL,
  PRIMARY KEY (`apartmentid`),
  INDEX `fk_apartment_building_idx` (`building` ASC),
  UNIQUE INDEX `apartmentid_UNIQUE` (`apartmentid` ASC),
  UNIQUE INDEX `apartmentname_UNIQUE` (`apartmentname` ASC),
  CONSTRAINT `fk_apartment_building`
    FOREIGN KEY (`building`)
    REFERENCES `domain-vermietet`.`building` (`buildingid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`landlord`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`landlord` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`landlord` (
  `landlordid` INT NOT NULL AUTO_INCREMENT,
  `userdetails` INT NOT NULL,
  PRIMARY KEY (`landlordid`),
  INDEX `fk_landlord_userdetails_idx` (`userdetails` ASC),
  UNIQUE INDEX `landlordid_UNIQUE` (`landlordid` ASC),
  CONSTRAINT `fk_landlord_userdetails`
    FOREIGN KEY (`userdetails`)
    REFERENCES `domain-vermietet`.`userdetails` (`userdetailsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`tenant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`tenant` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`tenant` (
  `tenantid` INT NOT NULL AUTO_INCREMENT,
  `userdetails` INT NOT NULL,
  PRIMARY KEY (`tenantid`),
  INDEX `fk_tenant_userdetails_idx` (`userdetails` ASC),
  UNIQUE INDEX `tenantid_UNIQUE` (`tenantid` ASC),
  CONSTRAINT `fk_tenant_userdetails`
    FOREIGN KEY (`userdetails`)
    REFERENCES `domain-vermietet`.`userdetails` (`userdetailsid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`rentalcontract`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`rentalcontract` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`rentalcontract` (
  `rentalcontractid` INT NOT NULL,
  `startdate` DATE NULL,
  PRIMARY KEY (`rentalcontractid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`rentedapartment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`rentedapartment` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`rentedapartment` (
  `rentedapartmentid` INT NOT NULL AUTO_INCREMENT,
  `apartment` INT NOT NULL,
  `landlord` INT NOT NULL,
  `tenant` INT NOT NULL,
  `rentalcontract` INT NOT NULL,
  PRIMARY KEY (`rentedapartmentid`),
  INDEX `fk_rentedapartment_apartment_idx` (`apartment` ASC),
  INDEX `fk_rentedapartment_landlord_idx` (`landlord` ASC),
  INDEX `fk_rentedapartment_tenant_idx` (`tenant` ASC),
  INDEX `fk_rentedapartment_rentalcontract_idx` (`rentalcontract` ASC),
  UNIQUE INDEX `fk_rentedapartment_apartment_landlord` (`apartment` ASC, `landlord` ASC),
  UNIQUE INDEX `rentedapartmentid_UNIQUE` (`rentedapartmentid` ASC),
  CONSTRAINT `fk_rentedapartment_apartment`
    FOREIGN KEY (`apartment`)
    REFERENCES `domain-vermietet`.`apartment` (`apartmentid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentedapartment_landlord`
    FOREIGN KEY (`landlord`)
    REFERENCES `domain-vermietet`.`landlord` (`landlordid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentedapartment_tenant`
    FOREIGN KEY (`tenant`)
    REFERENCES `domain-vermietet`.`tenant` (`tenantid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rentedapartment_rentalcontract`
    FOREIGN KEY (`rentalcontract`)
    REFERENCES `domain-vermietet`.`rentalcontract` (`rentalcontractid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`electricitycounter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`electricitycounter` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`electricitycounter` (
  `electricitycounterid` INT NOT NULL AUTO_INCREMENT,
  `apartment` INT NOT NULL,
  PRIMARY KEY (`electricitycounterid`),
  UNIQUE INDEX `fk_electricitycounter_apartment_idx` (`apartment` ASC),
  CONSTRAINT `fk_electricitycounter_apartment`
    FOREIGN KEY (`apartment`)
    REFERENCES `domain-vermietet`.`apartment` (`apartmentid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `domain-vermietet`.`electricityconsumption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domain-vermietet`.`electricityconsumption` ;

CREATE TABLE IF NOT EXISTS `domain-vermietet`.`electricityconsumption` (
  `electricityconsumptionid` INT NOT NULL AUTO_INCREMENT,
  `starttime` TIMESTAMP NOT NULL,
  `duration_in_seconds` INT NOT NULL,
  `amount_in_watts` FLOAT NOT NULL,
  `electricitycounter` INT NOT NULL,
  PRIMARY KEY (`electricityconsumptionid`),
  INDEX `fk_electricityconsumption_electricitycounter_idx` (`electricitycounter` ASC),
  CONSTRAINT `fk_electricityconsumption_electricitycounter`
    FOREIGN KEY (`electricitycounter`)
    REFERENCES `domain-vermietet`.`electricitycounter` (`electricitycounterid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
